### ISSUE TITLE
Failed to deploy in Qovery

### ISSUE THREAD

**Issue by samadii** [AsmSafone/RadioPlayerV2#1]
![Screenshot_2021-05-20-01-44-21](https://user-images.githubusercontent.com/77415087/118887181-3d5bb380-b90f-11eb-99b0-6595b7bb3685.png)

**Comment by AsmSafone** [comment]
Lol! Start voice chat first in the group/channel 😒
Start Voice Chat In The Chat Which ID Used in CHAT var. & Restart The Bot. Solved!
