### ISSUE TITLE
struct.error: unpack requires a buffer of 263 bytes

### ISSUE THREAD

**Issue by deulizealand** [AsmSafone/RadioPlayerV2#13]
I faced this error when try to run the program.
![image](https://user-images.githubusercontent.com/15981200/130785743-171cbc5b-e2a2-4f59-b88a-804f211ef6bb.png)

i run the program in VPS Linode with 1GB ram and 1 Core. 
hope you can help to solve. thanks

**Comment by AsmSafone** [comment]
use pyrogram session string!
